name: nAmE

ghc-options: -Wall -Wno-unused-matches -Wno-unused-do-bind
language: GHC2021
default-extensions:
  - OverloadedStrings
  - LambdaCase
  - RecursiveDo
  - DeriveGeneric
  - BlockArguments
  - TypeFamilies
  - FunctionalDependencies
  - RecordWildCards
  - ApplicativeDo
dependencies:
  - base
  - jsaddle
  - jsaddle-warp
  - reflex-dom
  - text
  - lens

executables:
  app:
    source-dirs: app
    main: Main.hs
